apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
  creationTimestamp: "2024-05-15T06:38:26Z"
  generation: 12
  labels:
    app.kubernetes.io/instance: thanos-querier-example-thanos
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/part-of: ThanosQuerier
  name: thanos-querier-example-thanos
  namespace: openstack
  ownerReferences:
  - apiVersion: monitoring.rhobs/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ThanosQuerier
    name: example-thanos
    uid: 29b35e8c-e2d9-486f-bdc7-4339cc634fc1
  resourceVersion: "458415"
  uid: 71ee94b1-5e32-49d2-8b92-09471a362783
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: thanos-querier-example-thanos
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: thanos-querier-example-thanos
        app.kubernetes.io/managed-by: observability-operator
        app.kubernetes.io/part-of: ThanosQuerier
      name: thanos-querier-example-thanos
      namespace: openstack
    spec:
      containers:
      - args:
        - query
        - --log.format=logfmt
        - --query.replica-label=prometheus_replica
        - --query.auto-downsampling
        - --endpoint=dnssrv+_grpc._tcp.metric-storage-thanos-sidecar.openstack.svc.cluster.local
        - --grpc-client-server-name=metric-storage-thanos-sidecar.openstack.svc.cluster.local
        - --grpc-client-tls-ca=/certs/ca/ca
        - --grpc-client-tls-secure
        - --http.config=/http/http.conf
        image: registry.redhat.io/cluster-observability-operator/coo-thanos-rhel8@sha256:09eab2acb7ea4241a4c60cf134c10f1250b772967dc6c495bc91653f4de1deeb
        imagePullPolicy: IfNotPresent
        name: thanos-querier
        ports:
        - containerPort: 10902
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /certs/ca
          name: ca
        - mountPath: /certs/web/cert
          name: web-cert
        - mountPath: /certs/web/key
          name: web-key
        - mountPath: /http
          name: http-conf
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ca
        secret:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca
          secretName: cert-thanos-sidecar-svc
      - name: web-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: cert
          secretName: cert-thanos-querier-svc
      - name: web-key
        secret:
          defaultMode: 420
          items:
          - key: tls.key
            path: key
          secretName: cert-thanos-querier-svc
      - configMap:
          defaultMode: 420
          name: thanos-http-conf
        name: http-conf
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-15T13:46:41Z"
    lastUpdateTime: "2024-05-15T13:46:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-15T06:38:26Z"
    lastUpdateTime: "2024-05-15T13:46:41Z"
    message: ReplicaSet "thanos-querier-example-thanos-676bb49d7d" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
